config/routes.rb
Rails.application.routes.draw do

  root to: 'articles#index'

  resources :articles do
    resources :comments
    resources :likes
  end

  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]

  get '/signup', to: 'users#new'
  resources :users, except: :new

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_comment, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]

  def new
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build
  end

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @article
    else
      render :new
    end
  end

  def destroy
    article = @comment.article

    if equal_with_current_user?(article.user)
      @comment.destroy
      redirect_to article
    else
      flash[:danger] = 'Wrong User!'
      redirect_to(root_path)
    end
  end

  def edit
    # @article = Article.find(params[:article_id])
    @article = @comment.article
  end

  def update
    @article = @comment.article

    if @comment.update comment_params
      redirect_to @article
    else
      render :edit
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end

  def correct_user
    unless equal_with_current_user?(@comment.user)
      flash[:danger] = 'Wrong User!'
      redirect_to(root_path) and return
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="column is-3 is-offset-5 comment">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.user.name %></strong> <small><%= time_ago_in_words(comment.created_at) %> ago </small>
          <br>
          <%= comment.body %>
        </p>
      </div>
      <nav class="level is-mobile">
      <% if equal_with_current_user?(comment.user) %>
        <div class="level-left">
          <%= link_to edit_article_comment_path(comment.article, comment), class: "level-item" do  %>
            <span class="icon is-small"><i class="fas fa-edit"></i></span>
          <% end %>
          <%= link_to  article_comment_path(comment.article.id, comment.id), method: :delete,
            class: "level-item", data: { confirm: "Are you sure you want to delete this comment?" } do %>
            <span class="icon is-small"><i class="far fa-trash-alt"></i></span>
          <% end %>
        </div>
      <% elsif equal_with_current_user?(comment.article.user) %>
        <div class="level-left">
          <%= link_to article_comment_path(comment.article, comment), method: :delete,
            class: "level-item", data: { confirm: "Are you sure you want to delete this comment?" } do %>
            <span class="icon is-small"><i class="fas fa-trash-alt"></i></span>
          <% end %>
        </div>
      <% end %>
      </nav>
    </div>
  </article>
</div>

app/views/comments/_form.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-5">
        <h1><%= heading %></h1>
      </div>
    </div>


    <% if comment.errors.any? %>
      <div class="column is-6 is-offset-3">
        <article class="message is-danger">
          <div class="message-body">
            <p><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</p>
            <br>
            <p>
            <% comment.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </p>
          </div>
        </article>
      </div>
    <% end %>



    <div class="column is-6 is-offset-3">
      <article class="media">
        <div class="media-content">
          <%= form_with model: [article, comment], local: true do |form| %>
            <%= current_user.name %>
            <div class="field">
              <%= form.label :body, class: "label" %>
              <p class="control">
                <%= form.text_area :body, class: "textarea", placeholder: "Add comment..." %>
              </p>
            </div>
            <nav class="level">
              <div class="level-left">
                <div class="level-item">
                  <%= form.submit submit, class: "button is-info" %>
                </div>
                <div class="level-item">
                  <%= link_to "Cancel", article_path(article), class: "button is-link" %>
                </div>
              </div>
            </nav>
          <% end %>
        </div>
      </article>
    </div>
  </div>
</div>

app/views/comments/edit.html.erb
<%= render 'form', article: @article, comment: @comment,
heading: "Edit #{@article.title}'s' Comment",
submit: "Update" %>

app/views/comments/new.html.erb
<%= render 'form', article: @article, comment: @comment,
heading: "#{@article.title} - New Comment",
submit: "Save" %>