config/routes.rb
Rails.application.routes.draw do

  root to: 'articles#index'

  resources :articles do
    resources :comments
    resources :likes
  end

  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]

  get '/signup', to: 'users#new'
  resources :users, except: :new

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
MINIMUM_TITLE_LENGTH = 5
MAXIMUM_TITLE_LENGTH = 40

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user

  validates :title, presence: true, length: { minimum: MINIMUM_TITLE_LENGTH, maximum: MAXIMUM_TITLE_LENGTH }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :require_login, only: [:index, :show]
  before_action :find_article, except: [:index, :new, :create]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
    @comments = @article.comments.order(id: :desc)
    # @comment = Comment.new
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      flash[:success] = 'Article created.'

      redirect_to @article
    else
      render :new
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end

  def find_article
    @article = Article.find(params[:id])
  end

  def correct_user
    unless equal_with_current_user?(@article.user)
      flash[:danger] = 'Wrong User'
      redirect_to(root_path) and return
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="column is-6 is-offset-3">
  <div class="card">
    <div class="card-content">
      <div class="content is-size-5">
      <% unless local_assigns[:show] %>
        <p class="title">
          <%= article.title %>
        </p>
      <% end %>
        <p class="subtitle">
          <%= article.body %>
        </p>
      </div>
    <time><p><small>Posted <%=time_ago_in_words(article.created_at).capitalize %> ago</small></p></time>
    <time><p><small><%= article.likes.count %> <%= (article.likes.count) == 1 ? 'Like' : 'Likes' %></small></p></time>
    </div>
    <footer class="card-footer">
      <% if local_assigns[:show] %>
        <%= link_to "Back", root_path, class: "card-footer-item" %>
      <% else %>
        <%= link_to "Show", article_path(article), class: "card-footer-item" %>
      <% end %>
      <% if logged_in? && equal_with_current_user?(article.user) %>
        <%= link_to "Edit", edit_article_path(article), class: "card-footer-item" %>
      <% end %>

      <% if local_assigns[:show] && logged_in? %>
        <%= link_to "Comment", new_article_comment_path(article), class: "card-footer-item" %>
        <%= render 'likes/like_unlike', class: "card-footer-item" %>
      <% end %>

      <% if logged_in? && equal_with_current_user?(article.user) %>
        <%= link_to "Delete", article_path(article), method: :delete,
            data: { confirm: "Are you sure you want to delete this article?" },
            class: "card-footer-item" %>
      <% end  %>
    </footer>
  </div>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1><%= heading %></h1>
      </div>
    </div>

    <% if article.errors.any? %>
      <div class="column is-6 is-offset-3">
        <article class="message is-danger">
          <div class="message-body">
            <p><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</p>
            <br>
            <p>
            <% article.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </p>
          </div>
        </article>
      </div>
    <% end %>

    <div class="column is-6 is-offset-3">
      <%= form_with model: article, local: true do |form| %>
        <div class="field">
          <%= form.label :title, class: "label" %>
          <div class="control">
            <%= form.text_field :title, class: "input", placeholder: "Title" %>
          </div>
          <% if article.errors.any? %>
            <p class="help is-danger">This title is invalid</p>
          <% end %>
        </div>
        <div class="field">
          <%= form.label :body, class: "label" %>

          <div class="control">
            <%= form.text_area :body, class: "textarea", placeholder: 'Your body' %>
          </div>
        </div>
        <div class="field is-grouped">
          <div class="control">
            <%= form.submit submit, class: "button is-link" %>
          </div>
          <div class="control">
            <%= link_to "Cancel", cancel_path, class: 'button is-link is-light' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<%= render 'form',
  article: @article,
  submit: 'Update Article',
  cancel_path: article_path(@article),
  heading: 'Edit Article' %>
  

app/views/articles/index.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h2>Articles</h2>
      </div>
    </div>
    <%= render @articles %>
  </div>
</div>

app/views/articles/new.html.erb
<%= render 'form',
  article: @article,
  submit: 'Save Article',
  cancel_path: root_path,
  heading: 'New Article' %>

app/views/articles/show.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1><%= @article.title %></h1>
      </div>
    </div>

    <%= render @article, show: true %>

    <%= render @comments %>
  </div>
</div>