config/routes.rb
Rails.application.routes.draw do

  root to: 'articles#index'

  resources :articles do
    resources :comments
    resources :likes
  end

  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]

  get '/signup', to: 'users#new'
  resources :users, except: :new

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  MAXIMUM_NAME_LENGTH = 255
  MAXIMUM_EMAIL_LENGTH = 50
  MINIMUM_PASSWORD_LENGTH = 6
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  MINIMUM_AGE = 18

  has_secure_password

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :profile_picture

  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'received_id'
  has_many :personal_messages, dependent: :destroy

  before_save :email_to_downcase

  validates :name, presence: true, length: { maximum: MAXIMUM_NAME_LENGTH }

  validates :email, presence: true, length: { maximum: MAXIMUM_EMAIL_LENGTH },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :password, presence: true, length: { minimum: MINIMUM_PASSWORD_LENGTH }

  validates :age, presence: true

  validate :at_least_18

  private

  def email_to_downcase
    self.email = email.downcase
  end

  def at_least_18
    errors.add(:age, 'must be at least 18') if age < MINIMUM_AGE
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, except: :show

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :profile_picture, :age)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<li>
  <%= user.name %> | <%= link_to 'send a message', new_personal_message_path(receiver_id: user) %>
</li>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="container">
  <div class="columns is-multiline">
    <% if @user.errors.any? %>
      <div class="column is-6 is-offset-3">
        <article class="message is-danger">
          <div class="message-body">
            <p><%= pluralize(@user.errors.count, "error") %> prohibited this article from being saved:</p>
            <br>
            <p>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </p>
          </div>
        </article>
      </div>
    <% end %>

    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1> Edit User Info </h1>
      </div>
    </div>

    <div class="column is-6 is-offset-3">
      <%= form_with model: @user, local: true do |form| %>
        <div class="field">
          <%= form.label "Profile Picture", class: "label" %>

          <div class="control">
            <%= form.file_field :profile_picture, placeholder: 'Attach photo' %>
          </div>
        </div>

        <div class="field">
          <%= form.label :name, class: "label" %>
          <div class="control">
            <%= form.text_field :name, class: "input", placeholder: "Your name" %>
          </div>
        </div>
        <div class="field">
          <%= form.label :email, class: "label" %>

          <div class="control">
            <%= form.email_field :email, class: "input", placeholder: 'Your email' %>
          </div>
        </div>

        <div class="field">
          <%= form.label :password, class: "label" %>

          <div class="control">
            <%= form.password_field :password, class: "input", placeholder: 'enter password' %>
          </div>
        </div>

        <div class="field">
          <%= form.label :password_confirmation, class: "label" %>

          <div class="control">
            <%= form.password_field :password_confirmation, class: "input", placeholder: 'confirm password' %>
          </div>
        </div>

        <div class="field">
          <%= form.label :age, class: "label" %>

          <div class="control">
            <%= form.number_field :age, class: "input", placeholder: 'enter your age..' %>
          </div>
        </div>

        <div class="field is-grouped">
          <div class="control">
            <%= form.submit "Save", class: "button is-link" %>
          </div>
          <div class="control">
            <%= link_to "Cancel", articles_path, class: 'button is-link is-light' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-5 is-offset-3">
      <div class="content is-size-6">
        <h1>Users</h1>

        <ul><%= render @users %></ul>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="columns is-multiline">
    <% if @user.errors.any? %>
      <div class="column is-6 is-offset-3">
        <article class="message is-danger">
          <div class="message-body">
            <p><%= pluralize(@user.errors.count, "error") %> prohibited this article from being saved:</p>
            <br>
            <p>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </p>
          </div>
        </article>
      </div>
    <% end %>

    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1> New User </h1>
      </div>
    </div>

    <div class="column is-6 is-offset-3">
      <%= form_with model: @user, local: true do |form| %>
        <div class="field">
          <%= form.label "Profile Picture", class: "label" %>

          <div class="control">
            <%= form.file_field :profile_picture, placeholder: 'Attach photo' %>
          </div>
        </div>

        <div class="field">
          <%= form.label :name, class: "label" %>
          <div class="control">
            <%= form.text_field :name, class: "input", placeholder: "Your name" %>
          </div>
        </div>
        <div class="field">
          <%= form.label :email, class: "label" %>

          <div class="control">
            <%= form.email_field :email, class: "input", placeholder: 'Your email' %>
          </div>
        </div>

        <div class="field">
          <%= form.label :password, class: "label" %>

          <div class="control">
            <%= form.password_field :password, class: "input", placeholder: 'enter password' %>
          </div>
        </div>

        <div class="field">
          <%= form.label :password_confirmation, class: "label" %>

          <div class="control">
            <%= form.password_field :password_confirmation, class: "input", placeholder: 'confirm password' %>
          </div>
        </div>

        <div class="field">
          <%= form.label :age, class: "label" %>

          <div class="control">
            <%= form.number_field :age, class: "input", placeholder: 'enter your age..' %>
          </div>
        </div>

        <div class="field is-grouped">
          <div class="control">
            <%= form.submit "Sign Up", class: "button is-link" %>
          </div>
          <div class="control">
            <%= link_to "Cancel", articles_path, class: 'button is-link is-light' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-8 is-offset-2">
      <div class="content is-size-3">
        <div class="box">
          <article class="media">
            <div class="media-left">
              <figure class="image is-128x128">
                <% if @user.profile_picture.attached? %>
                  <img src="<%=(url_for(@user.profile_picture))%>" alt="Image">
                <% else %>
                  <%= image_tag("default-avatar.png") %>
                <% end %>
              </figure>
            </div>
            <div class="media-content">
              <div class="content is-size-3">
                <p><strong><%= @user.name %></strong></p>
              </div>
              <div class="content is-size-5">
              <p><small><%= @user.email %></small></p>
              </div>
            </div>
            <div class="media-right">
              <div class="content is-size-5">
              <p><small><%= link_to 'Edit profile', edit_user_path(@user.id), class: "level-item" %></small></p>
                <%# <span class="icon is-small"><i class="fas fa-edit"></i></span> %>
              <%# <% end %>
              </div>
            </div>
          </article>
        </div>
      </div>
    </div>
    <%= render @user.articles %>
  </div>
</div>