config/routes.rb
Rails.application.routes.draw do

  root to: 'articles#index'

  resources :articles do
    resources :comments
    resources :likes
  end

  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]

  get '/signup', to: 'users#new'
  resources :users, except: :new

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flash.html.erb
<div class="container">
  <div class="columns is-multiline">
    <% flash.each do |name, msg| %>

    <div class="column is-6 is-offset-3">
      <div class= "notification is-<%= name %>">
        <button class="delete"></button>
        <%= msg %>
      </div>
    </div>

    <% end %>
  </div>
</div>

app/views/shared/_nav_bar.html.erb
<div class="container">
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <%= link_to "Home", root_path, class: "navbar-item is-size-1"%>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
          <% if logged_in? %>
            <%= link_to "New Article", new_article_path, class: "button has-text-weight-bold" %>
            <%= link_to "Log Out", logout_path, method: :delete, class: "button has-text-weight-bold" %>
            <%= link_to 'Users', users_path, class: "button has-text-weight-bold" %>
            <%= link_to 'Inbox', conversations_path, class: "button has-text-weight-bold" %>
            <figure class="image">
              <%= link_to user_path(current_user.id) do %>
                <% if current_user.profile_picture.attached? %>
                  <%= image_tag(current_user.profile_picture)%>
                <% else %>
                  <%= image_tag("default-avatar.png") %>
                <% end %>
              <% end %>
            </figure>
          <% else %>
            <%= link_to "Log In", login_path, class: "button has-text-weight-bold" %>
            <%= link_to "Sign Up", signup_path, class: "button has-text-weight-bold" %>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </nav>
</div>